### ISSUE TITLE
issues with current version

### ISSUE THREAD

**Issue by PaddyPat** [Lynx-Shortener/Lynx#104]
tryed it with docker and also with your demo instance and sharex integration (current version)

always get error:
https://privatebin.net/?acf1992f0659597a#Cc4tT8wpS2bsA14fnd3HSDUH6xRXoe4Wn4aFyux8w5yR

Error:
Invalid response content is returned from host (demo.getlynx.dev), expected response content is JSON.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.UploadersLib.CustomUploaderFunctionJson.Call(ShareXCustomUploaderSyntaxParser parser, String[] parameters)
   at ShareX.UploadersLib.ShareXCustomUploaderSyntaxParser.CallFunction(String functionName, String[] parameters)
   at ShareX.UploadersLib.ShareXSyntaxParser.Parse(String text, Boolean isFunction, Int32 startPosition, Int32& endPosition)
   at ShareX.UploadersLib.ShareXSyntaxParser.Parse(String text, Boolean isFunction, Int32 startPosition, Int32& endPosition)
   at ShareX.UploadersLib.ShareXSyntaxParser.Parse(String text)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, ResponseInfo responseInfo, UploaderErrorManager errors, CustomUploaderInput input, Boolean isShortenedURL)
   at ShareX.UploadersLib.CustomUploaderItem.TryParseResponse(UploadResult result, ResponseInfo responseInfo, UploaderErrorManager errors, CustomUploaderInput input, Boolean isShortenedURL)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://demo.getlynx.dev/api/sharex

Status code:
(500) Internal Server Error

Headers:
Transfer-Encoding: chunked
Connection: keep-alive
access-control-allow-credentials: *
access-control-allow-headers: *
access-control-allow-methods: *
access-control-allow-origin: *
alt-svc: h3=":443"; ma=86400
content-security-policy: default-src 'none'
source-server: dipper-v5 | jackbailey.dev
x-content-type-options: nosniff
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=f%2FdXsntfayb6LloulMeQTj6YkjplFCmodtYD28HVe6MspGihclN%2FsYDVPM8SzFKdlE%2BMpZ6AliWUxrKHOMYbOacj68yvquKUJJGivTjtCj7R3qMBPBoa9krfsJU%2FoF%2FgdcXM"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
CF-RAY: 83a8654c3a0237e3-FRA
Content-Type: text/html; charset=utf-8
Date: Sun, 24 Dec 2023 11:10:04 GMT
Server: cloudflare
X-Powered-By: Express

Response text:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

Image:
https://ibb.co/SRCHMxZ

**Comment by JackBailey** [comment]
It'll take me a few days to get to a computer to be able to test this out, but what docker tag are you using when running it yourself?

Latest, beta, :1 etc?

**Comment by PaddyPat** [comment]
image: jackbailey/lynx:1 and also latest

tried compose from your documentation:
https://github.com/Lynx-Shortener/Lynx/blob/main/docker-compose.yml

**Comment by JackBailey** [comment]
I can't seem to recreate this on the demo or a local docker instance. What ShareX version and device are you using?
